name: Docker Image CI for GHCR

on:
    push:
    workflow_dispatch:
jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Build and push the Image
              run: |
                docker login --username loganwhitten --password ${{ secrets.GH_PAT }} ghcr.io
                docker build . --tag ghcr.io/loganwhitten/site:latest
                docker push ghcr.io/loganwhitten/site:latest